export const resources = [
  {
    name: "একজন করোনা বিজয়ীর ইন্টারভিউ",
    type: "audio",
    url: "",
    content_id: 'corona_interview',
  },
  {
    name: "মহামারীর সময়ে মানসিক প্রস্তুতি",
    type: "audio",
    url: "",
    content_id: 'pandemic_preparation',
  },
  {
    name: "চিন্তার প্রভাব",
    type: "audio",
    url: "",
    content_id: 'thought_behaviour',
  },
  {
    name: "দাম্পত্য সম্পর্ক",
    type: "audio",
    url: "",
    content_id: 'couple_relationship',
  },
  {
    name: "রাগ নিয়ন্ত্রণ",
    type: "audio",
    url: "",
    content_id: 'anger_management',
  },
  {
    name: "ব্রিদিং এক্সারসাইজ",
    type: "audio",
    url: "",
    content_id: 'breathing',
  },
  {
    name: "অভিভাবক-সন্তানের সম্পর্ক",
    type: "audio",
    url: "",
    content_id: 'parent_child_relationship',
  },
  {
    name: "কথা বলার কিছু ধরন",
    type: "audio",
    url: "",
    content_id: 'communication_skill',
  },
  {
    name: "আবেগ নিয়ন্ত্রণ",
    type: "audio",
    url: "",
    content_id: 'emotion_management',
  },
  {
    name: "মাইন্ডফুলনেস",
    type: "audio",
    url: "",
    content_id: 'mindfulness',
  },
  {
    name: "প্রিয়জনের মৃত্যুর পর নিজেকে মানসিক ভাবে ঠিক রাখার উপায়",
    type: "audio",
    url: "",
    content_id: 'experiencing_grief_loss',
  },
  {
    name: "ঘুমের গুণগত মান বৃদ্ধি করার কৌশল",
    type: "audio",
    url: "",
    content_id: 'maximizing_sleep',
  },
  {
    name: "মাংসপেশির শিথিলায়ন",
    type: "audio",
    url: "",
    content_id: 'pmr',
  },
];
